overwrite: true
schema: ./schema/*.graphql
documents: ./document/*.graphql
generates:
  ./generated.tsx:
    plugins:
      - typescript
      - typescript-compatibility
      - typescript-operations
      - typescript-react-apollo
    config:
      withHooks: true
      withHOC: false
      withComponent: false